name: project-fishy   # avoids space in folder name becoming the project name

services:
  bot:
    build:
      context: .
      target: prod
    container_name: project-fishy-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      YTDL_NO_UPDATE: "1"
      PORT: "8889"
      # REGISTER_ON_BOOT: "true"   # (optional) run once then remove
    ports:
      - "8889:8889"
    # On Linux you can uncomment for lowest-latency UDP:
    # network_mode: "host"
